---
title: "Testing Multiple Iterations - Summary Stats"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)

zero_shot_multiple <- read.csv("outputs/data/zero_shot_results_multiple.csv")
one_shot_multiple <- read.csv("outputs/data/one_shot_results_multiple.csv")
few_shot_multiple <- read.csv("outputs/data/few_shot_single_results_multiple.csv")

```

# Zero shot learning

```{r zeroshot-summary, message=FALSE}
zero_shot_multiple <- read.csv("outputs/data/zero_shot_results_multiple.csv")

# Add iter variable
zero_shot_multiple <- zero_shot_multiple %>%
  mutate(iter = floor(X/120) + 1)

accuracy_racism <- rep(NA, nrow(zero_shot_multiple)/120)
accuracy_sexism <- rep(NA, nrow(zero_shot_multiple)/120)
accuracy_hate <- rep(NA, nrow(zero_shot_multiple)/120)
precision_racism <- rep(NA, nrow(zero_shot_multiple)/120)
precision_sexism <- rep(NA, nrow(zero_shot_multiple)/120)
precision_hate <- rep(NA, nrow(zero_shot_multiple)/120)
recall_racism <- rep(NA, nrow(zero_shot_multiple)/120)
recall_sexism <- rep(NA, nrow(zero_shot_multiple)/120)
recall_hate <- rep(NA, nrow(zero_shot_multiple)/120)
f1_racism <- rep(NA, nrow(zero_shot_multiple)/120)
f1_sexism <- rep(NA, nrow(zero_shot_multiple)/120)
f1_hate <- rep(NA, nrow(zero_shot_multiple)/120)

# For each iteration:
for (i in 1:(nrow(zero_shot_multiple)/120)){
  # Racism table
  zero_racism <- 
    zero_shot_multiple %>%
    filter(category == "racist" & iter == i) %>%
    select(category, label, answer, temperature) %>%
    mutate(answer = tolower(answer) %>% trimws(),
           label_yn = ifelse(grepl("not", label), "N", "Y"),
           answer_yn = case_when(str_detect(answer, "no") ~ "N",
                                str_detect(answer, "yes") ~ "Y",
                                TRUE ~ "Other")) %>%
    filter(answer_yn != "Other") %>%
    count(label_yn, answer_yn) %>%
    pivot_wider(names_from = answer_yn, values_from = n, values_fill = 0) %>%
    mutate(label_yn = case_when(label_yn == "N" ~ "Not racist",
                                label_yn == "Y" ~ "Racist")) %>%
    rename("Actual classification" = label_yn, "Not racist" = N, "Racist" = Y)
  zero_racism <- zero_racism[, c("Actual classification", "Not racist", "Racist")]
  
  # Sexism table
  zero_sexism <- 
    zero_shot_multiple %>%
    filter(category == "sexist" & iter == i) %>%
    select(category, label, answer, temperature) %>%
    mutate(answer = tolower(answer) %>% trimws(),
           label_yn = ifelse(grepl("not", label), "N", "Y"),
           answer_yn = case_when(str_detect(answer, "no") ~ "N",
                                str_detect(answer, "yes") ~ "Y",
                                TRUE ~ "Other")) %>%
    filter(answer_yn != "Other") %>%
    count(label_yn, answer_yn) %>%
    pivot_wider(names_from = answer_yn, values_from = n, values_fill = 0) %>%
    mutate(label_yn = case_when(label_yn == "N" ~ "Not sexist",
                                label_yn == "Y" ~ "Sexist")) %>%
    rename("Actual classification" = label_yn, "Not sexist" = N, "Sexist" = Y)
  zero_sexism <- zero_sexism[, c("Actual classification", "Not sexist", "Sexist")]
  
  # Hate table
  zero_hate <- 
    zero_shot_multiple %>%
    filter(iter == i) %>%
    select(category, label, answer, temperature) %>%
    mutate(answer = tolower(answer) %>% trimws(),
           label_yn = ifelse(grepl("not", label), "N", "Y"),
           answer_yn = case_when(str_detect(answer, "no") ~ "N",
                                str_detect(answer, "yes") ~ "Y",
                                TRUE ~ "Other")) %>%
    filter(answer_yn != "Other") %>%
    count(label_yn, answer_yn) %>%
    pivot_wider(names_from = answer_yn, values_from = n, values_fill = 0) %>%
    mutate(label_yn = case_when(label_yn == "N" ~ "Not hate speech",
                                label_yn == "Y" ~ "Hate speech")) %>%
    rename("Actual classification" = label_yn, "Not hate speech" = N, "Hate speech" = Y)
  zero_hate <- zero_hate[, c("Actual classification", "Not hate speech", "Hate speech")]
  
  # Compute accuracy/precision/recall/f1
  tp_r <- zero_racism[2, 3] %>% as.numeric()
  tn_r <- zero_racism[1, 2] %>% as.numeric()
  fp_r <- zero_racism[1, 3] %>% as.numeric()
  fn_r <- zero_racism[2, 2] %>% as.numeric()
  
  tp_s <- zero_sexism[2, 3] %>% as.numeric()
  tn_s <- zero_sexism[1, 2] %>% as.numeric()
  fp_s <- zero_sexism[1, 3] %>% as.numeric()
  fn_s <- zero_sexism[2, 2] %>% as.numeric()
  
  tp_h <- zero_hate[2, 3] %>% as.numeric()
  tn_h <- zero_hate[1, 2] %>% as.numeric()
  fp_h <- zero_hate[1, 3] %>% as.numeric()
  fn_h <- zero_hate[2, 2] %>% as.numeric()
  
  zero_racism_accuracy <- ((tp_r + tn_r)/(tp_r + tn_r + fp_r + fn_r)) %>% round(4)*100
  zero_racism_precision <- (tp_r/(tp_r + fp_r)) %>% round(4)*100
  zero_racism_recall <- (tp_r/(tp_r + fn_r)) %>% round(4)*100
  zero_racism_f1 <- ((2*zero_racism_precision*zero_racism_recall)/(zero_racism_precision + zero_racism_recall)) %>% round(2)

  zero_sexism_accuracy <- ((tp_s + tn_s)/(tp_s + tn_s + fp_s + fn_s)) %>% round(4)*100
  zero_sexism_precision <- (tp_s/(tp_s + fp_s)) %>% round(4)*100
  zero_sexism_recall <- (tp_s/(tp_s + fn_s)) %>% round(4)*100
  zero_sexism_f1 <- ((2*zero_sexism_precision*zero_sexism_recall)/(zero_sexism_precision + zero_sexism_recall)) %>% round(2)

  zero_hate_accuracy <- ((tp_h + tn_h)/(tp_h + tn_h + fp_h + fn_h)) %>% round(4)*100
  zero_hate_precision <- (tp_h/(tp_h + fp_h)) %>% round(4)*100
  zero_hate_recall <- (tp_h/(tp_h + fn_h)) %>% round(4)*100
  zero_hate_f1 <- ((2*zero_hate_precision*zero_sexism_recall)/(zero_hate_precision + zero_hate_recall)) %>% round(2)

  # Add to vectors
  accuracy_racism[i] <- zero_racism_accuracy
  accuracy_sexism[i] <- zero_sexism_accuracy
  accuracy_hate[i] <- zero_hate_accuracy
  precision_racism[i] <- zero_racism_precision
  precision_sexism[i] <- zero_sexism_precision
  precision_hate[i] <- zero_hate_precision
  recall_racism[i] <- zero_racism_recall
  recall_sexism[i] <- zero_sexism_recall
  recall_hate[i] <- zero_hate_recall
  f1_racism[i] <- zero_racism_f1
  f1_sexism[i] <- zero_sexism_f1
  f1_hate[i] <- zero_hate_f1
}

# Sample distributions of accuracy, precision, recall, and f1
zero_racism_summary <- cbind(iter = 1:length(accuracy_racism),
                             accuracy_racism,
                             precision_racism,
                             recall_racism,
                             f1_racism) %>% 
  as_tibble() %>%
  summarise(name = "Racism",
            calc = "Mean",
            accuracy = mean(accuracy_racism),
            precision = mean(precision_racism),
            recall = mean(recall_racism),
            f1 = mean(f1_racism)) %>%
  rbind(summarise(., name = "Racism",
                    calc = "SE",
                    accuracy = sd(accuracy_racism)/sqrt(n()),
                    precision = sd(precision_racism)/sqrt(n()),
                    recall = sd(recall_racism)/sqrt(n()),
                    f1 = sd(f1_racism)/sqrt(n())))


zero_sexism_summary <- cbind(iter = 1:length(accuracy_sexism),
                             accuracy_sexism,
                             precision_sexism,
                             recall_sexism,
                             f1_sexism) %>% 
  as_tibble() %>%
  summarise(name = "Sexism",
            calc = "Mean",
            accuracy = mean(accuracy_sexism),
            precision = mean(precision_sexism),
            recall = mean(recall_sexism),
            f1 = mean(f1_sexism)) %>%
  rbind(summarise(., name = "Sexism",
                  calc = "SE",
                  accuracy = sd(accuracy_sexism)/sqrt(n()),
                  precision = sd(precision_sexism)/sqrt(n()),
                  recall = sd(recall_sexism)/sqrt(n()),
                  f1 = sd(f1_sexism)/sqrt(n())))


zero_hate_summary <- cbind(iter = 1:length(accuracy_hate),
                             accuracy_hate,
                             precision_hate,
                             recall_hate,
                             f1_hate) %>% 
  as_tibble() %>%
  summarise(name = "Overall",
            calc = "Mean",
            accuracy = mean(accuracy_hate),
            precision = mean(precision_hate),
            recall = mean(recall_hate),
            f1 = mean(f1_hate)) %>%
  rbind(summarise(., name = "Overall",
                  calc = "SE",
                  accuracy = sd(accuracy_hate)/sqrt(n()),
                  precision = sd(precision_hate)/sqrt(n()),
                  recall = sd(recall_hate)/sqrt(n()),
                  f1 = sd(f1_hate)/sqrt(n())))

zero_summary <- rbind(zero_racism_summary, zero_sexism_summary, zero_hate_summary)

zero_summary %>% pivot_longer(cols = !c(name, calc), names_to = "metric") %>%
  pivot_wider(names_from = c(calc), values_from = value) %>%
  mutate(name = case_when(metric == "accuracy" ~ name, TRUE ~ ""),
         metric = str_to_title(metric),
         Mean = round(Mean),
         SE = round(SE, 1)) %>%
  knitr::kable(col.names = c("", "Metric", "Mean (%)", "Standard Error (%)"), 
        caption = "Performance of model in zero-shot learning across 100 classifications of each comment at a temperature of 0.3",
        booktabs = TRUE,
        linesep = "") %>%
  kableExtra::column_spec(column = 1, bold = TRUE)
```

# One shot learning

```{r oneshot-summary, message=FALSE}
one_shot_multiple <- read.csv("outputs/data/one_shot_results_multiple.csv")

# Add iter variable
one_shot_multiple <- one_shot_multiple %>%
  mutate(iter = floor(X/120) + 1)

accuracy_racism <- rep(NA, nrow(one_shot_multiple)/120)
accuracy_sexism <- rep(NA, nrow(one_shot_multiple)/120)
accuracy_hate <- rep(NA, nrow(one_shot_multiple)/120)
precision_racism <- rep(NA, nrow(one_shot_multiple)/120)
precision_sexism <- rep(NA, nrow(one_shot_multiple)/120)
precision_hate <- rep(NA, nrow(one_shot_multiple)/120)
recall_racism <- rep(NA, nrow(one_shot_multiple)/120)
recall_sexism <- rep(NA, nrow(one_shot_multiple)/120)
recall_hate <- rep(NA, nrow(one_shot_multiple)/120)
f1_racism <- rep(NA, nrow(one_shot_multiple)/120)
f1_sexism <- rep(NA, nrow(one_shot_multiple)/120)
f1_hate <- rep(NA, nrow(one_shot_multiple)/120)

# For each iteration:
for (i in 1:(nrow(one_shot_multiple)/120)){
  # Racism table
  one_racism <- 
    one_shot_multiple %>%
    filter(category == "racist" & iter == i) %>%
    select(category, label, answer, temperature) %>%
    mutate(answer = tolower(answer) %>% trimws(),
           label_yn = ifelse(grepl("not", label), "N", "Y"),
           answer_yn = case_when(str_detect(answer, "no") ~ "N",
                                str_detect(answer, "yes") ~ "Y",
                                TRUE ~ "Other")) %>%
    filter(answer_yn != "Other") %>%
    count(label_yn, answer_yn) %>%
    pivot_wider(names_from = answer_yn, values_from = n, values_fill = 0) %>%
    mutate(label_yn = case_when(label_yn == "N" ~ "Not racist",
                                label_yn == "Y" ~ "Racist")) %>%
    rename("Actual classification" = label_yn, "Not racist" = N, "Racist" = Y)
  one_racism <- one_racism[, c("Actual classification", "Not racist", "Racist")]
  
  # Sexism table
  one_sexism <- 
    one_shot_multiple %>%
    filter(category == "sexist" & iter == i) %>%
    select(category, label, answer, temperature) %>%
    mutate(answer = tolower(answer) %>% trimws(),
           label_yn = ifelse(grepl("not", label), "N", "Y"),
           answer_yn = case_when(str_detect(answer, "no") ~ "N",
                                str_detect(answer, "yes") ~ "Y",
                                TRUE ~ "Other")) %>%
    filter(answer_yn != "Other") %>%
    count(label_yn, answer_yn) %>%
    pivot_wider(names_from = answer_yn, values_from = n, values_fill = 0) %>%
    mutate(label_yn = case_when(label_yn == "N" ~ "Not sexist",
                                label_yn == "Y" ~ "Sexist")) %>%
    rename("Actual classification" = label_yn, "Not sexist" = N, "Sexist" = Y)
  one_sexism <- one_sexism[, c("Actual classification", "Not sexist", "Sexist")]
  
  # Hate table
  one_hate <- 
    one_shot_multiple %>%
    filter(iter == i) %>%
    select(category, label, answer, temperature) %>%
    mutate(answer = tolower(answer) %>% trimws(),
           label_yn = ifelse(grepl("not", label), "N", "Y"),
           answer_yn = case_when(str_detect(answer, "no") ~ "N",
                                str_detect(answer, "yes") ~ "Y",
                                TRUE ~ "Other")) %>%
    filter(answer_yn != "Other") %>%
    count(label_yn, answer_yn) %>%
    pivot_wider(names_from = answer_yn, values_from = n, values_fill = 0) %>%
    mutate(label_yn = case_when(label_yn == "N" ~ "Not hate speech",
                                label_yn == "Y" ~ "Hate speech")) %>%
    rename("Actual classification" = label_yn, "Not hate speech" = N, "Hate speech" = Y)
  one_hate <- one_hate[, c("Actual classification", "Not hate speech", "Hate speech")]
  
  # Compute accuracy/precision/recall/f1
  tp_r <- one_racism[2, 3] %>% as.numeric()
  tn_r <- one_racism[1, 2] %>% as.numeric()
  fp_r <- one_racism[1, 3] %>% as.numeric()
  fn_r <- one_racism[2, 2] %>% as.numeric()
  
  tp_s <- one_sexism[2, 3] %>% as.numeric()
  tn_s <- one_sexism[1, 2] %>% as.numeric()
  fp_s <- one_sexism[1, 3] %>% as.numeric()
  fn_s <- one_sexism[2, 2] %>% as.numeric()
  
  tp_h <- one_hate[2, 3] %>% as.numeric()
  tn_h <- one_hate[1, 2] %>% as.numeric()
  fp_h <- one_hate[1, 3] %>% as.numeric()
  fn_h <- one_hate[2, 2] %>% as.numeric()
  
  one_racism_accuracy <- ((tp_r + tn_r)/(tp_r + tn_r + fp_r + fn_r)) %>% round(4)*100
  one_racism_precision <- (tp_r/(tp_r + fp_r)) %>% round(4)*100
  one_racism_recall <- (tp_r/(tp_r + fn_r)) %>% round(4)*100
  one_racism_f1 <- ((2*one_racism_precision*one_racism_recall)/(one_racism_precision + one_racism_recall)) %>% round(2)

  one_sexism_accuracy <- ((tp_s + tn_s)/(tp_s + tn_s + fp_s + fn_s)) %>% round(4)*100
  one_sexism_precision <- (tp_s/(tp_s + fp_s)) %>% round(4)*100
  one_sexism_recall <- (tp_s/(tp_s + fn_s)) %>% round(4)*100
  one_sexism_f1 <- ((2*one_sexism_precision*one_sexism_recall)/(one_sexism_precision + one_sexism_recall)) %>% round(2)

  one_hate_accuracy <- ((tp_h + tn_h)/(tp_h + tn_h + fp_h + fn_h)) %>% round(4)*100
  one_hate_precision <- (tp_h/(tp_h + fp_h)) %>% round(4)*100
  one_hate_recall <- (tp_h/(tp_h + fn_h)) %>% round(4)*100
  one_hate_f1 <- ((2*one_hate_precision*one_sexism_recall)/(one_hate_precision + one_hate_recall)) %>% round(2)

  # Add to vectors
  accuracy_racism[i] <- one_racism_accuracy
  accuracy_sexism[i] <- one_sexism_accuracy
  accuracy_hate[i] <- one_hate_accuracy
  precision_racism[i] <- one_racism_precision
  precision_sexism[i] <- one_sexism_precision
  precision_hate[i] <- one_hate_precision
  recall_racism[i] <- one_racism_recall
  recall_sexism[i] <- one_sexism_recall
  recall_hate[i] <- one_hate_recall
  f1_racism[i] <- one_racism_f1
  f1_sexism[i] <- one_sexism_f1
  f1_hate[i] <- one_hate_f1
}

# Sample distributions of accuracy, precision, recall, and f1
one_racism_summary <- cbind(iter = 1:length(accuracy_racism),
                             accuracy_racism,
                             precision_racism,
                             recall_racism,
                             f1_racism) %>% 
  as_tibble() %>%
  summarise(name = "Racism",
            calc = "Mean",
            accuracy = mean(accuracy_racism),
            precision = mean(precision_racism),
            recall = mean(recall_racism),
            f1 = mean(f1_racism)) %>%
  rbind(summarise(., name = "Racism",
                    calc = "SE",
                    accuracy = sd(accuracy_racism)/sqrt(n()),
                    precision = sd(precision_racism)/sqrt(n()),
                    recall = sd(recall_racism)/sqrt(n()),
                    f1 = sd(f1_racism)/sqrt(n())))


one_sexism_summary <- cbind(iter = 1:length(accuracy_sexism),
                             accuracy_sexism,
                             precision_sexism,
                             recall_sexism,
                             f1_sexism) %>% 
  as_tibble() %>%
  summarise(name = "Sexism",
            calc = "Mean",
            accuracy = mean(accuracy_sexism),
            precision = mean(precision_sexism),
            recall = mean(recall_sexism),
            f1 = mean(f1_sexism)) %>%
  rbind(summarise(., name = "Sexism",
                  calc = "SE",
                  accuracy = sd(accuracy_sexism)/sqrt(n()),
                  precision = sd(precision_sexism)/sqrt(n()),
                  recall = sd(recall_sexism)/sqrt(n()),
                  f1 = sd(f1_sexism)/sqrt(n())))


one_hate_summary <- cbind(iter = 1:length(accuracy_hate),
                             accuracy_hate,
                             precision_hate,
                             recall_hate,
                             f1_hate) %>% 
  as_tibble() %>%
  summarise(name = "Overall",
            calc = "Mean",
            accuracy = mean(accuracy_hate),
            precision = mean(precision_hate),
            recall = mean(recall_hate),
            f1 = mean(f1_hate)) %>%
  rbind(summarise(., name = "Overall",
                  calc = "SE",
                  accuracy = sd(accuracy_hate)/sqrt(n()),
                  precision = sd(precision_hate)/sqrt(n()),
                  recall = sd(recall_hate)/sqrt(n()),
                  f1 = sd(f1_hate)/sqrt(n())))

one_summary <- rbind(one_racism_summary, one_sexism_summary, one_hate_summary)

one_summary %>% pivot_longer(cols = !c(name, calc), names_to = "metric") %>%
  pivot_wider(names_from = c(calc), values_from = value) %>%
  mutate(name = case_when(metric == "accuracy" ~ name, TRUE ~ ""),
         metric = str_to_title(metric),
         Mean = round(Mean),
         SE = round(SE, 1)) %>%
  knitr::kable(col.names = c("", "Metric", "Mean (%)", "Standard Error (%)"), 
        caption = "Performance of model in one-shot learning across 100 classifications of each comment at a temperature of 0.3",
        booktabs = TRUE,
        linesep = "") %>%
  kableExtra::column_spec(column = 1, bold = TRUE)
```
# Few-shot single category

```{r oneshot-summary, message=FALSE}
# Add iter variable
few_shot_multiple <- few_shot_multiple %>%
  mutate(iter = floor(X/120) + 1)

accuracy_racism <- rep(NA, nrow(few_shot_multiple)/120)
accuracy_sexism <- rep(NA, nrow(few_shot_multiple)/120)
accuracy_hate <- rep(NA, nrow(few_shot_multiple)/120)
precision_racism <- rep(NA, nrow(few_shot_multiple)/120)
precision_sexism <- rep(NA, nrow(few_shot_multiple)/120)
precision_hate <- rep(NA, nrow(few_shot_multiple)/120)
recall_racism <- rep(NA, nrow(few_shot_multiple)/120)
recall_sexism <- rep(NA, nrow(few_shot_multiple)/120)
recall_hate <- rep(NA, nrow(few_shot_multiple)/120)
f1_racism <- rep(NA, nrow(few_shot_multiple)/120)
f1_sexism <- rep(NA, nrow(few_shot_multiple)/120)
f1_hate <- rep(NA, nrow(few_shot_multiple)/120)

# For each iteration:
for (i in 1:(nrow(few_shot_multiple)/120)){
  # Racism table
  one_racism <- 
    few_shot_multiple %>%
    filter(category == "racist" & iter == i) %>%
    select(category, label, answer, temperature) %>%
    mutate(answer = tolower(answer) %>% trimws(),
           label_yn = ifelse(grepl("not", label), "N", "Y"),
           answer_yn = case_when(str_detect(answer, "no") ~ "N",
                                str_detect(answer, "yes") ~ "Y",
                                TRUE ~ "Other")) %>%
    filter(answer_yn != "Other") %>%
    count(label_yn, answer_yn) %>%
    pivot_wider(names_from = answer_yn, values_from = n, values_fill = 0) %>%
    mutate(label_yn = case_when(label_yn == "N" ~ "Not racist",
                                label_yn == "Y" ~ "Racist")) %>%
    rename("Actual classification" = label_yn, "Not racist" = N, "Racist" = Y)
  one_racism <- one_racism[, c("Actual classification", "Not racist", "Racist")]
  
  # Sexism table
  one_sexism <- 
    few_shot_multiple %>%
    filter(category == "sexist" & iter == i) %>%
    select(category, label, answer, temperature) %>%
    mutate(answer = tolower(answer) %>% trimws(),
           label_yn = ifelse(grepl("not", label), "N", "Y"),
           answer_yn = case_when(str_detect(answer, "no") ~ "N",
                                str_detect(answer, "yes") ~ "Y",
                                TRUE ~ "Other")) %>%
    filter(answer_yn != "Other") %>%
    count(label_yn, answer_yn) %>%
    pivot_wider(names_from = answer_yn, values_from = n, values_fill = 0) %>%
    mutate(label_yn = case_when(label_yn == "N" ~ "Not sexist",
                                label_yn == "Y" ~ "Sexist")) %>%
    rename("Actual classification" = label_yn, "Not sexist" = N, "Sexist" = Y)
  one_sexism <- one_sexism[, c("Actual classification", "Not sexist", "Sexist")]
  
  # Hate table
  one_hate <- 
    few_shot_multiple %>%
    filter(iter == i) %>%
    select(category, label, answer, temperature) %>%
    mutate(answer = tolower(answer) %>% trimws(),
           label_yn = ifelse(grepl("not", label), "N", "Y"),
           answer_yn = case_when(str_detect(answer, "no") ~ "N",
                                str_detect(answer, "yes") ~ "Y",
                                TRUE ~ "Other")) %>%
    filter(answer_yn != "Other") %>%
    count(label_yn, answer_yn) %>%
    pivot_wider(names_from = answer_yn, values_from = n, values_fill = 0) %>%
    mutate(label_yn = case_when(label_yn == "N" ~ "Not hate speech",
                                label_yn == "Y" ~ "Hate speech")) %>%
    rename("Actual classification" = label_yn, "Not hate speech" = N, "Hate speech" = Y)
  one_hate <- one_hate[, c("Actual classification", "Not hate speech", "Hate speech")]
  
  # Compute accuracy/precision/recall/f1
  tp_r <- one_racism[2, 3] %>% as.numeric()
  tn_r <- one_racism[1, 2] %>% as.numeric()
  fp_r <- one_racism[1, 3] %>% as.numeric()
  fn_r <- one_racism[2, 2] %>% as.numeric()
  
  tp_s <- one_sexism[2, 3] %>% as.numeric()
  tn_s <- one_sexism[1, 2] %>% as.numeric()
  fp_s <- one_sexism[1, 3] %>% as.numeric()
  fn_s <- one_sexism[2, 2] %>% as.numeric()
  
  tp_h <- one_hate[2, 3] %>% as.numeric()
  tn_h <- one_hate[1, 2] %>% as.numeric()
  fp_h <- one_hate[1, 3] %>% as.numeric()
  fn_h <- one_hate[2, 2] %>% as.numeric()
  
  one_racism_accuracy <- ((tp_r + tn_r)/(tp_r + tn_r + fp_r + fn_r)) %>% round(4)*100
  one_racism_precision <- (tp_r/(tp_r + fp_r)) %>% round(4)*100
  one_racism_recall <- (tp_r/(tp_r + fn_r)) %>% round(4)*100
  one_racism_f1 <- ((2*one_racism_precision*one_racism_recall)/(one_racism_precision + one_racism_recall)) %>% round(2)

  one_sexism_accuracy <- ((tp_s + tn_s)/(tp_s + tn_s + fp_s + fn_s)) %>% round(4)*100
  one_sexism_precision <- (tp_s/(tp_s + fp_s)) %>% round(4)*100
  one_sexism_recall <- (tp_s/(tp_s + fn_s)) %>% round(4)*100
  one_sexism_f1 <- ((2*one_sexism_precision*one_sexism_recall)/(one_sexism_precision + one_sexism_recall)) %>% round(2)

  one_hate_accuracy <- ((tp_h + tn_h)/(tp_h + tn_h + fp_h + fn_h)) %>% round(4)*100
  one_hate_precision <- (tp_h/(tp_h + fp_h)) %>% round(4)*100
  one_hate_recall <- (tp_h/(tp_h + fn_h)) %>% round(4)*100
  one_hate_f1 <- ((2*one_hate_precision*one_sexism_recall)/(one_hate_precision + one_hate_recall)) %>% round(2)

  # Add to vectors
  accuracy_racism[i] <- one_racism_accuracy
  accuracy_sexism[i] <- one_sexism_accuracy
  accuracy_hate[i] <- one_hate_accuracy
  precision_racism[i] <- one_racism_precision
  precision_sexism[i] <- one_sexism_precision
  precision_hate[i] <- one_hate_precision
  recall_racism[i] <- one_racism_recall
  recall_sexism[i] <- one_sexism_recall
  recall_hate[i] <- one_hate_recall
  f1_racism[i] <- one_racism_f1
  f1_sexism[i] <- one_sexism_f1
  f1_hate[i] <- one_hate_f1
}

# Sample distributions of accuracy, precision, recall, and f1
one_racism_summary <- cbind(iter = 1:length(accuracy_racism),
                             accuracy_racism,
                             precision_racism,
                             recall_racism,
                             f1_racism) %>% 
  as_tibble() %>%
  summarise(name = "Racism",
            calc = "Mean",
            accuracy = mean(accuracy_racism),
            precision = mean(precision_racism),
            recall = mean(recall_racism),
            f1 = mean(f1_racism)) %>%
  rbind(summarise(., name = "Racism",
                    calc = "SE",
                    accuracy = sd(accuracy_racism)/sqrt(n()),
                    precision = sd(precision_racism)/sqrt(n()),
                    recall = sd(recall_racism)/sqrt(n()),
                    f1 = sd(f1_racism)/sqrt(n())))


one_sexism_summary <- cbind(iter = 1:length(accuracy_sexism),
                             accuracy_sexism,
                             precision_sexism,
                             recall_sexism,
                             f1_sexism) %>% 
  as_tibble() %>%
  summarise(name = "Sexism",
            calc = "Mean",
            accuracy = mean(accuracy_sexism),
            precision = mean(precision_sexism),
            recall = mean(recall_sexism),
            f1 = mean(f1_sexism)) %>%
  rbind(summarise(., name = "Sexism",
                  calc = "SE",
                  accuracy = sd(accuracy_sexism)/sqrt(n()),
                  precision = sd(precision_sexism)/sqrt(n()),
                  recall = sd(recall_sexism)/sqrt(n()),
                  f1 = sd(f1_sexism)/sqrt(n())))


one_hate_summary <- cbind(iter = 1:length(accuracy_hate),
                             accuracy_hate,
                             precision_hate,
                             recall_hate,
                             f1_hate) %>% 
  as_tibble() %>%
  summarise(name = "Overall",
            calc = "Mean",
            accuracy = mean(accuracy_hate),
            precision = mean(precision_hate),
            recall = mean(recall_hate),
            f1 = mean(f1_hate)) %>%
  rbind(summarise(., name = "Overall",
                  calc = "SE",
                  accuracy = sd(accuracy_hate)/sqrt(n()),
                  precision = sd(precision_hate)/sqrt(n()),
                  recall = sd(recall_hate)/sqrt(n()),
                  f1 = sd(f1_hate)/sqrt(n())))

one_summary <- rbind(one_racism_summary, one_sexism_summary, one_hate_summary)

one_summary %>% pivot_longer(cols = !c(name, calc), names_to = "metric") %>%
  pivot_wider(names_from = c(calc), values_from = value) %>%
  mutate(name = case_when(metric == "accuracy" ~ name, TRUE ~ ""),
         metric = str_to_title(metric),
         Mean = round(Mean),
         SE = round(SE, 1)) %>%
  knitr::kable(col.names = c("", "Metric", "Mean (%)", "Standard Error (%)"), 
        caption = "Performance of model in one-shot learning across 100 classifications of each comment at a temperature of 0.3",
        booktabs = TRUE,
        linesep = "") %>%
  kableExtra::column_spec(column = 1, bold = TRUE)
```
